"""tour added

Revision ID: a8c4f1bee037
Revises: 2d53b45c797c
Create Date: 2023-05-01 14:12:52.709376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8c4f1bee037'
down_revision = '2d53b45c797c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airport_schedule',
    sa.Column('flight_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('city_from', sa.String(), nullable=True),
    sa.Column('city_to', sa.String(), nullable=True),
    sa.Column('airport_from', sa.String(), nullable=True),
    sa.Column('airport_to', sa.String(), nullable=True)
    )
    op.create_table('city',
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('city_name', sa.String(), nullable=False),
    sa.Column('airport_id', sa.Integer(), nullable=False),
    sa.Column('airport_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('city_id'),
    sa.UniqueConstraint('airport_id'),
    sa.UniqueConstraint('airport_name'),
    sa.UniqueConstraint('city_name')
    )
    op.create_table('tour',
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('tour_name', sa.String(), nullable=False),
    sa.Column('city_from', sa.String(), nullable=False),
    sa.Column('city_to', sa.String(), nullable=False),
    sa.Column('airline_name', sa.String(), nullable=True),
    sa.Column('flight_start', sa.TIMESTAMP(), nullable=True),
    sa.Column('flight_end', sa.TIMESTAMP(), nullable=True),
    sa.Column('flight_price', sa.DECIMAL(), nullable=True),
    sa.PrimaryKeyConstraint('tour_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tour')
    op.drop_table('city')
    op.drop_table('airport_schedule')
    # ### end Alembic commands ###
