"""changed TIMESTAMP params

Revision ID: 704fe7a136ad
Revises: a8c4f1bee037
Create Date: 2023-05-01 22:47:33.248564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704fe7a136ad'
down_revision = 'a8c4f1bee037'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    op.alter_column('tour', 'flight_start', existing_type=sa.TIMESTAMP, type_=sa.TIMESTAMP(timezone=True))
    op.alter_column('tour', 'flight_end', existing_type=sa.TIMESTAMP, type_=sa.TIMESTAMP(timezone=True))
    op.alter_column('airport_schedule', 'flight_date', existing_type=sa.TIMESTAMP, type_=sa.TIMESTAMP(timezone=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
